### ISSUE TITLE
Last Image is only then available if we close the video window with ESC

### ISSUE THREAD

**Issue by Can-Inal** [Aspragas/Slider#1]
video: Video = Video()
    video.read('resources/videos/dog.mp4')
    video.show('Dog Video - ESC to Exit')
    video.release()

    Logger.critical('video released.')

    last_frame: Image = video.get_last_frame()
    last_frame.show('Last frame')

this code is not showing the last frame of video instance. Does not matter if i release video after `last_frame.show('Last frame')` or before.

### ERROR MESSAGE

**Traceback (most recent call last):
  File "c:\Dev\Slider\src\main.py", line 23, in <module>
    last_frame.show('Last frame')
  File "c:\Dev\Slider\src\materials\image.py", line 29, in show
    cv.imshow(window_title, self._image_matrix)
cv2.error: OpenCV(4.8.1) :-1: error: (-5:Bad argument) in function 'imshow'
Overload resolution failed:
mat data type = 17 is not supported
Expected Ptr<cv::cuda::GpuMat> for argument 'mat'
Expected Ptr<cv::UMat> for argument 'mat'**

**Comment by Can-Inal** [comment]
Issue fixed with latest [commit](https://github.com/Aspragas/Slider/commit/19a7e21aa072c86847ab8b6623f462846ceba505). Closing this issue!
